SELECT F1.ID, N.FISH_NAME, F1.LENGTH
FROM FISH_INFO F1
JOIN (SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE) F2
ON F1.LENGTH = F2.MAX_LENGTH AND F1.FISH_TYPE = F2.FISH_TYPE
JOIN FISH_NAME_INFO N
ON F1.FISH_TYPE = N.FISH_TYPE
ORDER BY ID